{{- if eq (include "twentycrm.bundledDb" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twentycrm.dbName" . }}
  namespace: {{ include "twentycrm.namespace" . }}
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgresql.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "twentycrm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
{{- end }}
