{{- if .Values.server.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "twentycrm.serverName" . }}
  namespace: {{ include "twentycrm.namespace" . }}
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.server.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.server.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "twentycrm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
